[functions.publish-website]
verify_jwt = false

[functions.create-guest-order]
verify_jwt = false

[functions.create-showroom-appointment]
verify_jwt = false

[functions.notify-new-appointment]
verify_jwt = true

[functions.notify-new-order]
verify_jwt = true

[functions.track-order]
verify_jwt = false
