[functions.publish-website]
verify_jwt = false

[functions.create-guest-order]
verify_jwt = false

[functions.create-showroom-appointment]
verify_jwt = false

[functions.upload-payment-qr]
verify_jwt = false
