import Link from 'next/link'
import { HelpCenterShell, HelpTip } from '../../../components/HelpCenter'

export default function GettingStartedPage() {
  return <HelpCenterShell current="/help/getting-started">
    <p className="eyebrow">Help Center</p><h1>Getting Started with Gel Blasters</h1>
    <p className="help-intro">New to gel blasters? This guide covers the basics, choosing your first unit, batteries, gel balls, maintenance, shipping, and showroom visits.</p>

    <section><h2>What is a gel blaster?</h2><p>Gel blasters are toy blasters that use approximately 7–8 mm hydrated gel balls as ammunition. Their mechanism is similar to an electric airsoft unit, but they generally operate at lower power.</p><p>Customers are responsible for following all applicable local rules and venue requirements. This guide is not formal legal advice.</p></section>
    <HelpTip warning><h2>Transport and use gel blasters responsibly</h2><p>Never carry or display a gel blaster openly in public. Even when used as a toy, it may be mistaken for a real firearm and cause public alarm.</p><ul><li>Keep the unit inside a bag or protective case while travelling.</li><li>Use it only at proper game sites or on private property with permission.</li><li>Keep an orange tip installed to help distinguish it from a real firearm.</li><li>Do not handle, display, or test-fire it in public places.</li><li>Always be considerate of the people around you.</li></ul></HelpTip>

    <section id="toy-vs-hobby"><h2>Toy Grade vs Hobby Grade</h2><p>At Hydro Blasters MNL, we believe that the best gel blaster is the one that fits your budget and how you plan to enjoy the hobby.</p><div className="help-split"><div><h3>Toy Grade</h3><p>Toy-grade gel blasters are a great choice for customers who simply want to try the hobby or enjoy casual play without spending heavily.</p><p>They are generally not designed for future upgrades. In addition, most toy-grade models cannot be <strong>practically</strong> repaired if they develop internal issues because replacement internal parts are generally not readily available on the market.</p><p>If you&apos;re simply looking to experience the hobby without a large investment, a toy-grade model may still be the right choice.</p></div><div><h3>Hobby Grade</h3><p>Hobby-grade gel blasters are intended for players who expect to stay in the hobby.</p><p>They are built around more standardized components, making repairs, maintenance, and upgrades much more practical because replacement parts are generally much easier to find.</p></div></div><HelpTip><h3>Hydro Tip</h3><p>If you&apos;re simply trying the hobby, a toy-grade blaster may be all you need.</p><p>If you think you&apos;ll stay in the hobby, starting with a hobby-grade model can save money in the long run because repairs and upgrades are usually much more practical.</p></HelpTip><p>Check the <strong>Upgradeable</strong> specification on each product page to see whether a model is hobby grade or toy grade.</p></section>
    <section><h2>Nylon gears versus metal gears</h2><p>Metal gears do not automatically make a gel blaster more powerful. Performance between nylon and metal gears may be similar. The main advantage of metal gears is generally durability, which may help them last longer under regular use or upgrades.</p></section>
    <section><h2>7.4V versus 11.1V batteries</h2><ul><li>Many gel blasters include a 7.4V battery.</li><li>An 11.1V battery can increase rate of fire.</li><li>It does not automatically increase FPS.</li><li>It may place additional stress on gears, the gearbox, wiring, trigger contacts, and other internal components.</li><li>Confirm that your specific unit is compatible before upgrading.</li></ul></section>
    <HelpTip><h2>Hydro Tip</h2><p>An 11.1V battery can make your blaster fire faster, not necessarily harder.</p></HelpTip>
    <section><h2>Charging the battery</h2><ul><li>Charging commonly takes around 2–4 hours, depending on the battery and charger.</li><li>Observe the charger’s indicator light. Its behavior can vary by charger.</li><li>Follow the instructions supplied with the battery and charger.</li><li>Do not leave charging batteries unattended.</li><li>Disconnect the battery from the unit when it is not in use.</li><li>Confirm plug orientation before connecting it.</li></ul></section>
    <section><h2>Hydrating and storing gel balls</h2><ul><li>Soak compatible gel balls for around 4 hours unless the product instructions state otherwise.</li><li>Drain excess water before loading.</li><li>Store hydrated gels in a clean airtight container to reduce shrinking.</li><li>Use properly sized, good-quality gel balls to reduce feeding issues.</li><li>Factory-supplied gel balls may not always provide the best feeding performance.</li></ul></section>
    <section><h2>Empty the magazine after use</h2><p>Remove remaining gel balls after using the unit. Gel balls left inside a magazine can shrink, deform, or contribute to feeding and jamming problems.</p></section>
    <HelpTip><h2>Hydro Tip</h2><p>Empty your magazine after every game to help prevent future feeding problems.</p></HelpTip>
    <section><h2>Avoid dry firing</h2><p>Avoid repeatedly firing the unit without properly prepared gel balls. Excessive dry firing may contribute to unnecessary wear, air-seal issues, or poor compression depending on the unit.</p></section>
    <section><h2>Semi-auto use</h2><p>We do not recommend rapid repeated use of semi-auto mode. Rapid semi-auto firing draws more power and can generate additional heat in the trigger contacts, wiring, and related electrical components.</p><p>Customers should use semi-auto at a sensible pace and allow the unit to cool if it becomes unusually warm. Repeated rapid use increases electrical stress and is not recommended, although it does not mean immediate failure will always occur.</p></section>
    <section><h2>Repairs and upgrades</h2><p>For repairs and upgrades, customers may contact Hydro Blasters MNL for guidance regarding the current partner technician and available service arrangements.</p><p><Link href="/policies/warranty">Read the Limited Warranty Policy</Link> or <Link href="/shop">browse the catalogue</Link>.</p></section>
  </HelpCenterShell>
}
import { createPageMetadata } from '../../../lib/seo'

export const metadata = createPageMetadata({ title: 'Getting Started Guide | Hydro Blasters MNL', description: 'Learn gel blaster basics, toy grade versus hobby grade, batteries, maintenance, and choosing your first unit.', path: '/help/getting-started' })
