import Link from 'next/link'
import { HelpCenterShell, HelpTip } from '../../../components/HelpCenter'

export default function WarrantyPage() {
  return <HelpCenterShell current="/policies/warranty"><p className="eyebrow">Store Policy</p><h1>Limited Warranty Policy</h1><HelpTip><h2>30-day limited warranty for manufacturing defects only.</h2></HelpTip>
    <section><h2>Coverage</h2><p>The limited warranty covers manufacturing defects in eligible gel blaster products supplied by Hydro Blasters MNL. The warranty is valid for 30 days from the date of purchase.</p></section>
    <section><h2>Not covered</h2><ul><li>Misuse, abuse, neglect, or accidents</li><li>Improper handling or failure to follow supplied instructions</li><li>Normal wear and tear</li><li>Customer modifications, alterations, unauthorized repairs, or disassembly</li><li>Incompatible batteries, chargers, ammunition, parts, or upgrades</li><li>Incorrect installation or user error</li><li>Cosmetic issues that do not affect normal function</li><li>Consumable or wear components unless failure is caused by a confirmed manufacturing defect</li></ul></section>
    <HelpTip warning><h2>Modifications</h2><p>Any modification, internal upgrade, unauthorized repair, or alteration may void the warranty.</p></HelpTip>
    <section><h2>Warranty remedy</h2><p>If a valid manufacturing defect is confirmed, Hydro Blasters MNL may repair the unit, replace the defective part, or replace the product, depending on the assessment and available stock.</p></section>
    <section><h2>Claim process</h2><ol><li>Contact Hydro Blasters MNL through the official Facebook account.</li><li>Provide the order details and a clear description of the issue.</li><li>Submit a clear video showing the defect for initial assessment.</li><li>Follow the provided testing or troubleshooting instructions.</li><li>If physical inspection is required, send the item to our trusted partner technician, JomarX Hobby Shop, located in Biñan, Laguna.</li></ol><p>The customer is responsible for the cost of sending the item to JomarX Hobby Shop for inspection.</p><p>If the issue is confirmed as a covered manufacturing defect, covered parts and labor will be provided without charge.</p><p>Return shipping arrangements should be confirmed with Hydro Blasters MNL after assessment.</p></section>
    <section><h2>Liability limitation</h2><p>Hydro Blasters MNL’s responsibility under this limited warranty is limited to the approved repair, replacement part, or product replacement. Hydro Blasters MNL is not responsible for losses or damage caused by misuse, unsafe handling, unauthorized modifications, or use outside the product’s intended purpose, to the extent allowed by applicable law.</p><p><Link href="/help/getting-started">Read Getting Started</Link> · <Link href="/policies/shipping">Shipping Policy</Link> · <Link href="/help/faq">FAQ</Link></p></section>
  </HelpCenterShell>
}
import { createPageMetadata } from '../../../lib/seo'

export const metadata = createPageMetadata({ title: 'Warranty Policy | Hydro Blasters MNL', description: 'Read Hydro Blasters MNL warranty coverage, care guidance, and the warranty claim process.', path: '/policies/warranty' })
